name: blog workflow
on:
  pull-request:
    branches:
      - main
  # creates workflow UI button
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  update-readme:
    name: Update this repo's README with the latest changes
    runs-on: ubuntu-latest
    continue-on-error: false
    steps: 
        - uses: actions/checkout@v4

        